name: Linux_Container_Nginx_Workflow

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: 'webapp-dev-atl-09876'
  CONTAINER_REGISTRY: 'joaolms/tests'

jobs:
  build-and-delivery:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Auth, build and push docker image
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        docker build . -t ${{ env.CONTAINER_REGISTRY }}:v${GITHUB_RUN_NUMBER} -f Dockerfile
        docker tag ${{ env.CONTAINER_REGISTRY }}:v${GITHUB_RUN_NUMBER} ${{ env.CONTAINER_REGISTRY }}:latest
        docker push ${{ env.CONTAINER_REGISTRY }}:v${GITHUB_RUN_NUMBER}
        docker push ${{ env.CONTAINER_REGISTRY }}:latest

  deploy:

    needs: [build-and-delivery]
    runs-on: ubuntu-latest

    steps:
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Web App for Container'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} 
        images: ${{ env.CONTAINER_REGISTRY }}:v${{ github.run_number }}
